//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTP
    {
        public int Id { get; set; }
        public string Ngay { get; set; }
        public int STTChuyen_SanPham { get; set; }
        public int STT { get; set; }
        public int CumId { get; set; }
        public int BTPNgay { get; set; }
        public System.TimeSpan TimeUpdate { get; set; }
        public Nullable<int> CommandTypeId { get; set; }
        public bool IsEndOfLine { get; set; }
        public bool IsEnterByKeypad { get; set; }
        public bool IsBTP_PB_HC { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Chuyen_SanPham Chuyen_SanPham { get; set; }
        public virtual Cum Cum { get; set; }
    }
}
