//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHienThi
    {
        public int MaHienThi { get; set; }
        public int STT { get; set; }
        public int SoLed { get; set; }
        public Nullable<int> IDMain { get; set; }
        public Nullable<int> IDMat { get; set; }
        public int IDCell { get; set; }
    }
}
