//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuyen
    {
        public Chuyen()
        {
            this.Chuyen_SanPham = new HashSet<Chuyen_SanPham>();
            this.Cums = new HashSet<Cum>();
            this.MapIdSanPhamNgays = new HashSet<MapIdSanPhamNgay>();
            this.P_DailyMapper = new HashSet<P_DailyMapper>();
            this.P_LineWorkingShift = new HashSet<P_LineWorkingShift>();
            this.P_PlayVideoShedule = new HashSet<P_PlayVideoShedule>();
            this.P_ReadPercentOfLine = new HashSet<P_ReadPercentOfLine>();
            this.SOUND_ReadConfig = new HashSet<SOUND_ReadConfig>();
            this.ThoiGianTinhNhipDoTTs = new HashSet<ThoiGianTinhNhipDoTT>();
            this.TheoDoiNgays = new HashSet<TheoDoiNgay>();
        }
    
        public int MaChuyen { get; set; }
        public string Code { get; set; }
        public string TenChuyen { get; set; }
        public string DinhNghia { get; set; }
        public string Sound { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> IdDen { get; set; }
        public Nullable<int> IdDenNangSuat { get; set; }
        public Nullable<int> IdTyLeDoc { get; set; }
        public Nullable<bool> IsEndDate { get; set; }
        public Nullable<int> IdTiLeBTPConLai { get; set; }
        public int LaoDongDinhBien { get; set; }
        public int IntSTT { get; set; }
        public int STTReadNS { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual P_LightPercent P_LightPercent { get; set; }
        public virtual ICollection<Chuyen_SanPham> Chuyen_SanPham { get; set; }
        public virtual ReadPercent ReadPercent { get; set; }
        public virtual ICollection<Cum> Cums { get; set; }
        public virtual ICollection<MapIdSanPhamNgay> MapIdSanPhamNgays { get; set; }
        public virtual ICollection<P_DailyMapper> P_DailyMapper { get; set; }
        public virtual ICollection<P_LineWorkingShift> P_LineWorkingShift { get; set; }
        public virtual ICollection<P_PlayVideoShedule> P_PlayVideoShedule { get; set; }
        public virtual ICollection<P_ReadPercentOfLine> P_ReadPercentOfLine { get; set; }
        public virtual ICollection<SOUND_ReadConfig> SOUND_ReadConfig { get; set; }
        public virtual ICollection<ThoiGianTinhNhipDoTT> ThoiGianTinhNhipDoTTs { get; set; }
        public virtual ICollection<TheoDoiNgay> TheoDoiNgays { get; set; }
    }
}
