//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public Config()
        {
            this.Config_App = new HashSet<Config_App>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }
        public string ValueDefault { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Config_App> Config_App { get; set; }
    }
}
