//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_App
    {
        public int Id { get; set; }
        public int ConfigId { get; set; }
        public int AppId { get; set; }
        public string Value { get; set; }
    
        public virtual Config Config { get; set; }
    }
}
