//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Den
    {
        public int STT { get; set; }
        public string Color { get; set; }
        public int ValueFrom { get; set; }
        public int ValueTo { get; set; }
        public Nullable<int> IdCatalogTable { get; set; }
        public Nullable<int> STTParent { get; set; }
        public Nullable<int> MaMauDen { get; set; }
    }
}
