//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public Error()
        {
            this.NangSuat_CumLoi = new HashSet<NangSuat_CumLoi>();
        }
    
        public int Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupErrorId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual GroupError GroupError { get; set; }
        public virtual ICollection<NangSuat_CumLoi> NangSuat_CumLoi { get; set; }
    }
}
