//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyPad_Object
    {
        public int Id { get; set; }
        public int KeyPadId { get; set; }
        public Nullable<int> STTNut { get; set; }
        public int ClusterId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CommandTypeId { get; set; }
        public int TypeOfKeypad { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Cum Cum { get; set; }
        public virtual KeyPad KeyPad { get; set; }
    }
}
