//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCDConfig
    {
        public int Id { get; set; }
        public int TableType { get; set; }
        public int RowType { get; set; }
        public Nullable<int> Column { get; set; }
        public string FontName { get; set; }
        public Nullable<double> FontSize { get; set; }
        public Nullable<int> FontStyle { get; set; }
        public string Color { get; set; }
        public string Background { get; set; }
        public Nullable<bool> FontWeight { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public bool IsDeleted { get; set; }
    }
}
