//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_SCHEDULE
    {
        public int Id { get; set; }
        public Nullable<int> MailTemplateId { get; set; }
        public string Time { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAIL_TEMPLATE MAIL_TEMPLATE { get; set; }
    }
}
