//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_TYPE
    {
        public MAIL_TYPE()
        {
            this.MAIL_SEND = new HashSet<MAIL_SEND>();
        }
    
        public int id { get; set; }
        public string TypeName { get; set; }
        public string note { get; set; }
        public bool active { get; set; }
        public string host { get; set; }
        public string port { get; set; }
    
        public virtual ICollection<MAIL_SEND> MAIL_SEND { get; set; }
    }
}
