//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_TEMPLATE
    {
        public MAIL_TEMPLATE()
        {
            this.MAIL_SCHEDULE = new HashSet<MAIL_SCHEDULE>();
            this.MAIL_T_M = new HashSet<MAIL_T_M>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public int MailSendId { get; set; }
        public string MailReceiveIds { get; set; }
        public string MailFileIds { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<MAIL_SCHEDULE> MAIL_SCHEDULE { get; set; }
        public virtual MAIL_SEND MAIL_SEND { get; set; }
        public virtual ICollection<MAIL_T_M> MAIL_T_M { get; set; }
    }
}
