//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_SEND
    {
        public MAIL_SEND()
        {
            this.MAIL_TEMPLATE = new HashSet<MAIL_TEMPLATE>();
        }
    
        public int Id { get; set; }
        public int MailTypeId { get; set; }
        public string Address { get; set; }
        public string PassWord { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAIL_TYPE MAIL_TYPE { get; set; }
        public virtual ICollection<MAIL_TEMPLATE> MAIL_TEMPLATE { get; set; }
    }
}
