//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NangSuat_CumLoi
    {
        public int Id { get; set; }
        public string Ngay { get; set; }
        public int STTChuyenSanPham { get; set; }
        public int CumId { get; set; }
        public int ErrorId { get; set; }
        public int SoLuongTang { get; set; }
        public int SoLuongGiam { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Cum Cum { get; set; }
        public virtual Error Error { get; set; }
    }
}
