//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_AssignCompletion
    {
        public P_AssignCompletion()
        {
            this.P_CompletionPhase_Daily = new HashSet<P_CompletionPhase_Daily>();
        }
    
        public int Id { get; set; }
        public int OrderIndex { get; set; }
        public int CommoId { get; set; }
        public int ProductionsPlan { get; set; }
        public bool IsFinish { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual ICollection<P_CompletionPhase_Daily> P_CompletionPhase_Daily { get; set; }
    }
}
