//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_DailyKeypadPosition
    {
        public int Id { get; set; }
        public int DailyPlanId { get; set; }
        public int KeypadId { get; set; }
        public int KCS_Day { get; set; }
        public int TC_Day { get; set; }
        public int Error_Day { get; set; }
        public int BTP_Day { get; set; }
        public int BTP_HC_Day { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual P_DailyPlans P_DailyPlans { get; set; }
        public virtual P_Keypad P_Keypad { get; set; }
    }
}
