//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_DailyPlans
    {
        public P_DailyPlans()
        {
            this.P_DailyInfo = new HashSet<P_DailyInfo>();
            this.P_DailyKeypadPosition = new HashSet<P_DailyKeypadPosition>();
            this.P_DailyKeypadRegister = new HashSet<P_DailyKeypadRegister>();
        }
    
        public int Id { get; set; }
        public int Index { get; set; }
        public int CSP_Id { get; set; }
        public string Date { get; set; }
        public int Labors { get; set; }
        public double LeanKH { get; set; }
        public double LaborProductivity { get; set; }
        public double NormsOfDay { get; set; }
        public int KCS_Day { get; set; }
        public int TC_Day { get; set; }
        public int Error_Day { get; set; }
        public int BTP_Day { get; set; }
        public int BTP_HC_Day { get; set; }
        public int BTPInLine { get; set; }
        public double Pace_TC { get; set; }
        public double Pace_TT { get; set; }
        public double Pace_SX { get; set; }
        public bool IsEndDate { get; set; }
        public bool ShowLCD { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<P_DailyInfo> P_DailyInfo { get; set; }
        public virtual ICollection<P_DailyKeypadPosition> P_DailyKeypadPosition { get; set; }
        public virtual ICollection<P_DailyKeypadRegister> P_DailyKeypadRegister { get; set; }
        public virtual Chuyen_SanPham Chuyen_SanPham { get; set; }
    }
}
