//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_DailyKeypadRegister
    {
        public P_DailyKeypadRegister()
        {
            this.P_KeypadRegis_Detail = new HashSet<P_KeypadRegis_Detail>();
        }
    
        public int Id { get; set; }
        public int DailyPlansId { get; set; }
        public int KeypadId { get; set; }
        public int EmployeeId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual P_DailyPlans P_DailyPlans { get; set; }
        public virtual P_Employee P_Employee { get; set; }
        public virtual P_Keypad P_Keypad { get; set; }
        public virtual ICollection<P_KeypadRegis_Detail> P_KeypadRegis_Detail { get; set; }
    }
}
