//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_DailyInfo
    {
        public int Id { get; set; }
        public int DailyPlansId { get; set; }
        public int KeypadId { get; set; }
        public int PhaseId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Time { get; set; }
        public int OutputType { get; set; }
        public bool IsEnterByKeypad { get; set; }
        public bool IsAdd { get; set; }
    
        public virtual P_DailyPlans P_DailyPlans { get; set; }
        public virtual P_Keypad P_Keypad { get; set; }
    }
}
