//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Department
    {
        public P_Department()
        {
            this.P_DepartmentDailyLabour = new HashSet<P_DepartmentDailyLabour>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BaseLabours { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<P_DepartmentDailyLabour> P_DepartmentDailyLabour { get; set; }
    }
}
