//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Employee
    {
        public P_Employee()
        {
            this.P_DailyKeypadRegister = new HashSet<P_DailyKeypadRegister>();
        }
    
        public int Id { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public bool Sex { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<P_DailyKeypadRegister> P_DailyKeypadRegister { get; set; }
    }
}
