//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_HistoryPressedKeypad
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public int LineId { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
