//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_LineWorkingShift
    {
        public int Id { get; set; }
        public int ShiftOrder { get; set; }
        public int LineId { get; set; }
        public int ShiftId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Chuyen Chuyen { get; set; }
        public virtual P_WorkingShift P_WorkingShift { get; set; }
    }
}
