//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_LightPercent
    {
        public P_LightPercent()
        {
            this.Chuyens = new HashSet<Chuyen>();
            this.P_LightPercent_De = new HashSet<P_LightPercent_De>();
            this.P_ReadPercentOfLine = new HashSet<P_ReadPercentOfLine>();
            this.P_ReadPercentOfLine1 = new HashSet<P_ReadPercentOfLine>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Chuyen> Chuyens { get; set; }
        public virtual ICollection<P_LightPercent_De> P_LightPercent_De { get; set; }
        public virtual ICollection<P_ReadPercentOfLine> P_ReadPercentOfLine { get; set; }
        public virtual ICollection<P_ReadPercentOfLine> P_ReadPercentOfLine1 { get; set; }
    }
}
