//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MonthlyProductionPlans
    {
        public int Id { get; set; }
        public int STT_C_SP { get; set; }
        public int ProductionPlans { get; set; }
        public int LK_TH { get; set; }
        public int LK_TC { get; set; }
        public int LK_BTP { get; set; }
        public int LK_BTP_HC { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Chuyen_SanPham Chuyen_SanPham { get; set; }
    }
}
