//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PhaseDaily
    {
        public int Id { get; set; }
        public int NangSuatId { get; set; }
        public int PhaseId { get; set; }
        public int Quantity { get; set; }
        public int CommandTypeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual NangXuat NangXuat { get; set; }
        public virtual P_Phase P_Phase { get; set; }
    }
}
