//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ReadPercent_KCSInventory_De
    {
        public int Id { get; set; }
        public int KCSInventoryId { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public string SoundPath { get; set; }
        public int RepeatTimes { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual P_ReadPercent_KCSInventory P_ReadPercent_KCSInventory { get; set; }
    }
}
