//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ReadPercent_KCSInventory
    {
        public P_ReadPercent_KCSInventory()
        {
            this.P_ReadPercent_KCSInventory_De = new HashSet<P_ReadPercent_KCSInventory_De>();
            this.P_ReadPercentOfLine = new HashSet<P_ReadPercentOfLine>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<P_ReadPercent_KCSInventory_De> P_ReadPercent_KCSInventory_De { get; set; }
        public virtual ICollection<P_ReadPercentOfLine> P_ReadPercentOfLine { get; set; }
    }
}
