//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaoHetHang> BaoHetHangs { get; set; }
        public DbSet<CatalogTable> CatalogTables { get; set; }
        public DbSet<ChiTietHienThi> ChiTietHienThis { get; set; }
        public DbSet<Chuyen> Chuyens { get; set; }
        public DbSet<Config> Configs { get; set; }
        public DbSet<Config_App> Config_App { get; set; }
        public DbSet<Cum> Cums { get; set; }
        public DbSet<Den> Dens { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<Floor> Floors { get; set; }
        public DbSet<GroupError> GroupErrors { get; set; }
        public DbSet<KeyPad> KeyPads { get; set; }
        public DbSet<KeyPad_Object> KeyPad_Object { get; set; }
        public DbSet<LCDConfig> LCDConfigs { get; set; }
        public DbSet<MAIL_FILE> MAIL_FILE { get; set; }
        public DbSet<MAIL_RECEIVE> MAIL_RECEIVE { get; set; }
        public DbSet<MAIL_SCHEDULE> MAIL_SCHEDULE { get; set; }
        public DbSet<MAIL_SEND> MAIL_SEND { get; set; }
        public DbSet<MAIL_T_M> MAIL_T_M { get; set; }
        public DbSet<MAIL_TEMPLATE> MAIL_TEMPLATE { get; set; }
        public DbSet<MAIL_TYPE> MAIL_TYPE { get; set; }
        public DbSet<MapIdSanPhamNgay> MapIdSanPhamNgays { get; set; }
        public DbSet<NangSuat_Cum> NangSuat_Cum { get; set; }
        public DbSet<NangSuat_CumLoi> NangSuat_CumLoi { get; set; }
        public DbSet<NangXuat> NangXuats { get; set; }
        public DbSet<P_AssignCompletion> P_AssignCompletion { get; set; }
        public DbSet<P_CompletionPhase> P_CompletionPhase { get; set; }
        public DbSet<P_CompletionPhase_Daily> P_CompletionPhase_Daily { get; set; }
        public DbSet<P_DailyInfo> P_DailyInfo { get; set; }
        public DbSet<P_DailyKeypadPosition> P_DailyKeypadPosition { get; set; }
        public DbSet<P_DailyKeypadRegister> P_DailyKeypadRegister { get; set; }
        public DbSet<P_DailyMapper> P_DailyMapper { get; set; }
        public DbSet<P_DailyPlans> P_DailyPlans { get; set; }
        public DbSet<P_Employee> P_Employee { get; set; }
        public DbSet<P_HistoryPressedKeypad> P_HistoryPressedKeypad { get; set; }
        public DbSet<P_Keypad> P_Keypad { get; set; }
        public DbSet<P_KeypadRegis_Detail> P_KeypadRegis_Detail { get; set; }
        public DbSet<P_LightPercent> P_LightPercent { get; set; }
        public DbSet<P_LightPercent_De> P_LightPercent_De { get; set; }
        public DbSet<P_LineWorkingShift> P_LineWorkingShift { get; set; }
        public DbSet<P_MonthlyProductionPlans> P_MonthlyProductionPlans { get; set; }
        public DbSet<P_Phase> P_Phase { get; set; }
        public DbSet<P_Phase_Assign_Log> P_Phase_Assign_Log { get; set; }
        public DbSet<P_PhaseDaily> P_PhaseDaily { get; set; }
        public DbSet<P_PhaseDailyLog> P_PhaseDailyLog { get; set; }
        public DbSet<P_PlayVideoShedule> P_PlayVideoShedule { get; set; }
        public DbSet<P_PlayVideoSheduleDetail> P_PlayVideoSheduleDetail { get; set; }
        public DbSet<P_ReadPercent_KCSInventory> P_ReadPercent_KCSInventory { get; set; }
        public DbSet<P_ReadPercent_KCSInventory_De> P_ReadPercent_KCSInventory_De { get; set; }
        public DbSet<P_ReadPercentOfLine> P_ReadPercentOfLine { get; set; }
        public DbSet<P_VideoLibrary> P_VideoLibrary { get; set; }
        public DbSet<P_WorkingShift> P_WorkingShift { get; set; }
        public DbSet<ReadPercent> ReadPercents { get; set; }
        public DbSet<SanLuongCat> SanLuongCats { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<Shift> Shifts { get; set; }
        public DbSet<ShowLCD_Config> ShowLCD_Config { get; set; }
        public DbSet<ShowLCD_LabelArea> ShowLCD_LabelArea { get; set; }
        public DbSet<ShowLCD_LabelForPanelContent> ShowLCD_LabelForPanelContent { get; set; }
        public DbSet<ShowLCD_Panel> ShowLCD_Panel { get; set; }
        public DbSet<ShowLCD_TableLayoutPanel> ShowLCD_TableLayoutPanel { get; set; }
        public DbSet<SOUND> SOUNDs { get; set; }
        public DbSet<SOUND_IntConfig> SOUND_IntConfig { get; set; }
        public DbSet<SOUND_ReadConfig> SOUND_ReadConfig { get; set; }
        public DbSet<SOUND_ReadConfigDetail> SOUND_ReadConfigDetail { get; set; }
        public DbSet<SOUND_TimeConfig> SOUND_TimeConfig { get; set; }
        public DbSet<SoundInt> SoundInts { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<ThanhPham> ThanhPhams { get; set; }
        public DbSet<ThoiGianTinhNhipDoTT> ThoiGianTinhNhipDoTTs { get; set; }
        public DbSet<ToCat> ToCats { get; set; }
        public DbSet<TTHienThi> TTHienThis { get; set; }
        public DbSet<TurnCOMMng> TurnCOMMngs { get; set; }
        public DbSet<TheoDoiNgay> TheoDoiNgays { get; set; }
        public DbSet<BTP> BTPs { get; set; }
        public DbSet<Chuyen_SanPham> Chuyen_SanPham { get; set; }
    }
}
