//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadPercent
    {
        public ReadPercent()
        {
            this.Chuyens = new HashSet<Chuyen>();
            this.P_ReadPercentOfLine = new HashSet<P_ReadPercentOfLine>();
        }
    
        public int Id { get; set; }
        public int PercentFrom { get; set; }
        public int PercentTo { get; set; }
        public int CountRepeat { get; set; }
        public string Sound { get; set; }
        public Nullable<int> IdParent { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Chuyen> Chuyens { get; set; }
        public virtual ICollection<P_ReadPercentOfLine> P_ReadPercentOfLine { get; set; }
    }
}
