//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanLuongCat
    {
        public int Id { get; set; }
        public int IdToCat { get; set; }
        public int IdSanPham { get; set; }
        public int SanLuong { get; set; }
        public System.TimeSpan ThoiGianNapSL { get; set; }
        public System.DateTime NgayNapSL { get; set; }
        public bool IsDeleted { get; set; }
    }
}
