//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowLCD_TableLayoutPanel
    {
        public int Id { get; set; }
        public string ColumnInt { get; set; }
        public string RowInt { get; set; }
        public string TableLayoutPanelName { get; set; }
        public Nullable<double> SizePercent { get; set; }
        public bool IsShow { get; set; }
        public int TableType { get; set; }
    }
}
