//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowLCD_LabelArea
    {
        public int Id { get; set; }
        public string Font { get; set; }
        public double Size { get; set; }
        public bool Bold { get; set; }
        public bool Italic { get; set; }
        public string Color { get; set; }
        public Nullable<int> Position { get; set; }
        public string TableLayoutPanelName { get; set; }
        public int TableType { get; set; }
        public string Note { get; set; }
    }
}
