//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowLCD_LabelForPanelContent
    {
        public int id { get; set; }
        public string LabelName { get; set; }
        public string SystemValueName { get; set; }
        public int IntRowTBLPanelContent { get; set; }
        public int SttNext { get; set; }
        public bool IsShow { get; set; }
        public int TableType { get; set; }
        public string Note { get; set; }
    }
}
