//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUND_ReadConfig
    {
        public SOUND_ReadConfig()
        {
            this.SOUND_ReadConfigDetail = new HashSet<SOUND_ReadConfigDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ConfigType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int IdChuyen { get; set; }
    
        public virtual Chuyen Chuyen { get; set; }
        public virtual ICollection<SOUND_ReadConfigDetail> SOUND_ReadConfigDetail { get; set; }
    }
}
