//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUND_ReadConfigDetail
    {
        public int Id { get; set; }
        public int IdReadConfig { get; set; }
        public Nullable<int> IdSound { get; set; }
        public Nullable<int> IdIntConfig { get; set; }
        public int IntType { get; set; }
        public int OrderIndex { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SOUND SOUND { get; set; }
        public virtual SOUND_IntConfig SOUND_IntConfig { get; set; }
        public virtual SOUND_ReadConfig SOUND_ReadConfig { get; set; }
    }
}
