//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPham
    {
        public int Id { get; set; }
        public string Ngay { get; set; }
        public int STTChuyen_SanPham { get; set; }
        public double NangXuatLaoDong { get; set; }
        public bool ShowLCD { get; set; }
        public int LaoDongChuyen { get; set; }
        public double LeanKH { get; set; }
        public double HieuSuat { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Chuyen_SanPham Chuyen_SanPham { get; set; }
    }
}
