//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoiNgay
    {
        public int STT { get; set; }
        public int MaChuyen { get; set; }
        public int CumId { get; set; }
        public int STTChuyenSanPham { get; set; }
        public int MaSanPham { get; set; }
        public int ThanhPham { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Date { get; set; }
        public Nullable<int> CommandTypeId { get; set; }
        public Nullable<int> ProductOutputTypeId { get; set; }
        public Nullable<int> ErrorId { get; set; }
        public bool IsEndOfLine { get; set; }
        public bool IsEnterByKeypad { get; set; }
    
        public virtual Chuyen Chuyen { get; set; }
        public virtual Cum Cum { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
