//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGianTinhNhipDoTT
    {
        public int Id { get; set; }
        public string Ngay { get; set; }
        public int MaChuyen { get; set; }
        public System.TimeSpan ThoiGianBatDau { get; set; }
    
        public virtual Chuyen Chuyen { get; set; }
    }
}
