//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToCat
    {
        public int IdToCat { get; set; }
        public string TenToCat { get; set; }
        public string DinhNghia { get; set; }
        public bool IsDeleted { get; set; }
        public int IdFloor { get; set; }
    }
}
