//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTHienThi
    {
        public int MaHienThi { get; set; }
        public int MaChuyen { get; set; }
        public int ViTri { get; set; }
        public int ChangeTP { get; set; }
        public int ChangeBTP { get; set; }
        public int IsInt { get; set; }
        public int IdCatalogTable { get; set; }
        public Nullable<int> STTDen { get; set; }
    }
}
